version: '3'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: journal
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
